version: '3'

services:
  api:
    container_name: comments-api
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 80:8000
    volumes:
     - ./:/app
    depends_on:
      - postgres
      - redis
    networks:
      - simple-network
    stdin_open: true
    tty: true
  postgres:
    image: postgres:16-alpine
    container_name: comments-db
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql
    networks:
      - simple-network
  redis:
   image: redis:alpine
   container_name: comments-redis
   networks:
      - simple-network

networks:
  simple-network: