# Generated by Django 5.1.4 on 2025-01-06 20:40

import django.core.validators
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_file_alter_comment_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[320, 240], upload_to='comment_images/', validators=[django.core.validators.FileExtensionValidator(['txt'])]),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[320, 240], upload_to='post_images/', validators=[django.core.validators.FileExtensionValidator(['txt'])]),
        ),
    ]
